-- Sample data for the Oxro Labs workspace. Run in the Supabase SQL editor AFTER you have signed up and created the workspace.
-- Safe to re-run: it does nothing if the workspace already has transactions. Dates are relative to today.
-- (GENERATED by scripts/_gen_seed.mjs — GSTINs carry valid checksums.)
do $$
declare v_org uuid; v_user uuid;
begin
  select m.org_id, m.user_id into v_org, v_user
  from public.org_members m where m.role = 'admin' order by m.created_at limit 1;
  if v_org is null then raise exception 'No workspace found. Sign in to the app and create the workspace first.'; end if;
  if exists (select 1 from public.entries where org_id = v_org) then raise notice 'Workspace already has data; seed skipped.'; return; end if;

  -- the approval trigger consults auth.uid(), which is null in the SQL editor; seeded rows are pre-approved
  alter table public.entries disable trigger entries_approval_guard;

  update public.orgs set gstin = '27AABCF1234F1Z4', opening_balance = 150000, monthly_goal = 100000 where id = v_org;

  insert into public.parties (org_id, kind, name, gstin, phone, email, created_by) values
    (v_org, 'customer', 'Sharma Traders', '27AAPFS0939F1ZX', '9876543210', 'accounts@sharma.example', v_user),
    (v_org, 'customer', 'Bluebird Retail', '29AABCB4521K1ZP', '9812345678', null, v_user),
    (v_org, 'customer', 'Kaveri Foods', '33AAACK7788L1ZZ', null, 'pay@kaveri.example', v_user),
    (v_org, 'vendor', 'Apex Machinery', '27AAECA5566M1Z8', null, null, v_user),
    (v_org, 'vendor', 'Metro Packaging', '27AAGCM2190B1ZR', null, null, v_user);

  insert into public.entries (org_id, user_id, created_by, kind, number, party, gstin, category, date, due_date, taxable, gst_rate, supply, paid_date, approval) values
    (v_org, v_user, v_user, 'sale', 'INV-101', 'Sharma Traders', '27AAPFS0939F1ZX', null, current_date + (-75), current_date + (-60), 48000, 18, 'intra', current_date + (-58), 'approved'),
    (v_org, v_user, v_user, 'sale', 'INV-102', 'Bluebird Retail', '29AABCB4521K1ZP', null, current_date + (-62), current_date + (-47), 82000, 18, 'inter', current_date + (-40), 'approved'),
    (v_org, v_user, v_user, 'sale', 'INV-103', 'Kaveri Foods', '33AAACK7788L1ZZ', null, current_date + (-41), current_date + (-26), 36000, 18, 'inter', current_date + (-20), 'approved'),
    (v_org, v_user, v_user, 'sale', 'INV-104', 'Sharma Traders', '27AAPFS0939F1ZX', null, current_date + (-33), current_date + (-18), 61000, 18, 'intra', current_date + (-15), 'approved'),
    (v_org, v_user, v_user, 'sale', 'INV-105', 'Bluebird Retail', '29AABCB4521K1ZP', null, current_date + (-20), current_date + (-5), 94000, 18, 'inter', null, 'approved'),
    (v_org, v_user, v_user, 'sale', 'INV-106', 'Kaveri Foods', '33AAACK7788L1ZZ', null, current_date + (-6), current_date + (9), 27000, 18, 'inter', null, 'approved'),
    (v_org, v_user, v_user, 'purchase', 'B-77', 'Apex Machinery', '27AAECA5566M1Z8', null, current_date + (-55), current_date + (-40), 52000, 18, 'intra', current_date + (-38), 'approved'),
    (v_org, v_user, v_user, 'purchase', 'B-81', 'Metro Packaging', '27AAGCM2190B1ZR', null, current_date + (-28), current_date + (-13), 31000, 18, 'intra', current_date + (-12), 'approved'),
    (v_org, v_user, v_user, 'purchase', 'B-90', 'QuickPrint (no GSTIN)', null, null, current_date + (-9), current_date + (6), 14000, 18, 'intra', null, 'approved'),
    (v_org, v_user, v_user, 'purchase', 'B-91', 'Apex Machinery', '27AAECA5566M1Z8', null, current_date + (-3), current_date + (12), 44000, 18, 'intra', null, 'approved'),
    (v_org, v_user, v_user, 'expense', 'RENT-OCT', 'City Properties', null, 'Rent', current_date + (-7), current_date + (-2), 25000, 0, 'intra', current_date + (-2), 'approved'),
    (v_org, v_user, v_user, 'expense', 'SW-221', 'CloudBooks SaaS', '29AABCC8899K1ZR', 'Software', current_date + (-15), current_date + (-15), 4200, 18, 'inter', current_date + (-15), 'approved'),
    (v_org, v_user, v_user, 'salary', 'PAY-SEP', 'Team payroll', null, null, current_date + (-38), current_date + (-35), 90000, 0, 'intra', current_date + (-35), 'approved'),
    (v_org, v_user, v_user, 'salary', 'PAY-OCT', 'Team payroll', null, null, current_date + (-8), current_date + (-5), 90000, 0, 'intra', null, 'approved');

  insert into public.recurring (org_id, user_id, kind, party, category, taxable, gst_rate, day_of_month, start_month, last_generated) values
    (v_org, v_user, 'expense', 'City Properties', 'Rent', 25000, 0, 1, to_char(current_date, 'YYYY-MM'), to_char(current_date, 'YYYY-MM'));

  insert into public.filings (org_id, user_id, type, period, due_date, filed_date, amount) values
    (v_org, v_user, 'GSTR1', to_char(current_date - interval '2 months', 'YYYY-MM'), (date_trunc('month', current_date - interval '1 month') + interval '10 days')::date, (date_trunc('month', current_date - interval '1 month') + interval '8 days')::date, 0),
    (v_org, v_user, 'GSTR3B', to_char(current_date - interval '2 months', 'YYYY-MM'), (date_trunc('month', current_date - interval '1 month') + interval '19 days')::date, (date_trunc('month', current_date - interval '1 month') + interval '17 days')::date, 18400);

  -- a 3-day check-in streak and a first XP balance for the admin
  insert into public.xp_events (user_id, kind, ref, day, xp) values
    (v_user, 'checkin', to_char(current_date - 2, 'YYYY-MM-DD'), to_char(current_date - 2, 'YYYY-MM-DD'), 10),
    (v_user, 'checkin', to_char(current_date - 1, 'YYYY-MM-DD'), to_char(current_date - 1, 'YYYY-MM-DD'), 10),
    (v_user, 'filing_on_time', 'GSTR3B:seed', to_char(current_date - 5, 'YYYY-MM-DD'), 40)
  on conflict do nothing;

  alter table public.entries enable trigger entries_approval_guard;
  raise notice 'Seeded % parties, % entries, 1 recurring template, 2 filings.', 5, 14;
end $$;
