// GENERATED by scripts/sync-env.mjs from .env. Public values only.
export const CONFIG = {
  SUPABASE_URL: "https://qljazetkcycptbcpmsdl.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsamF6ZXRrY3ljcHRiY3Btc2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEzOTU5OTksImV4cCI6MjEwNjk3MTk5OX0.Azcsl6b-WuU6A__yXfLOjqFz4g6O_KWiYshYE1JjtDw",
};
