"""Generates app/theme-light.generated.css from app/app.css.

app.css is dark-first and still has ~40 hard-coded dark colours. For every rule that has one, this emits an
`html[data-theme="light"]` override with the dark surface colours inverted to light ones (hue kept, lightness flipped).
Rules whose text colour is hard-coded white (dark chips, gradient cards, primary buttons) are left alone.
Re-run after editing app.css:   python scripts/gen_light_theme.py
Hand-written fixes live in app/theme.css (they win over this file)."""
import colorsys, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'app', 'app.css'), encoding='utf8').read()
src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)

COLOR = re.compile(r'#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b|rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*(?:,\s*[\d.]+\s*)?\)')


def parse(c):
    if c.startswith('#'):
        h = c[1:]; h = ''.join(x * 2 for x in h) if len(h) == 3 else h
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), 1.0
    n = [float(x) for x in re.findall(r'[\d.]+', c)]
    return int(n[0]), int(n[1]), int(n[2]), (n[3] if len(n) > 3 else 1.0)


def hls(c):
    r, g, b, a = parse(c); h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255); return h, l, s, a


def fmt(h, l, s, a):
    r, g, b = [round(x * 255) for x in colorsys.hls_to_rgb(h, max(0, min(1, l)), max(0, min(1, s)))]
    return f'rgba({r}, {g}, {b}, {a:g})' if a < 1 else f'#{r:02x}{g:02x}{b:02x}'


def invert_surface(c):
    h, l, s, a = hls(c)
    if l < 0.3: return fmt(h, 0.99 - l * 0.6, s * 0.55, a)
    return c


def soften_shadow(c):
    h, l, s, a = hls(c)
    return fmt(h, l, s, round(a * 0.3, 3)) if l < 0.2 else c


def darken_text(c):
    h, l, s, a = hls(c)
    return fmt(h, 0.27, min(1, s + 0.05), a) if (s >= 0.25 and l >= 0.55) else c


def tx_props(decl):
    out = []
    for m in re.finditer(r'([\w-]+)\s*:\s*([^;]+);?', decl):
        prop, val = m.group(1).strip(), m.group(2).strip()
        if prop in ('background', 'background-color', 'background-image', 'border', 'border-color', 'border-top', 'border-bottom', 'border-left', 'border-right', 'outline'):
            new = COLOR.sub(lambda x: invert_surface(x.group(0)), val)
        elif prop == 'box-shadow':
            new = COLOR.sub(lambda x: soften_shadow(x.group(0)), val)
        elif prop == 'color':
            new = COLOR.sub(lambda x: darken_text(x.group(0)), val)
        else: continue
        if new != val: out.append(f'  {prop}: {new};')
    return out


def has_white_text(decl):
    m = re.search(r'(?:^|;)\s*color\s*:\s*([^;]+)', decl)
    if not m: return False
    cs = COLOR.findall(m.group(1))
    if not cs: return m.group(1).strip() in ('white',)
    h, l, s, a = hls(cs[0]); return l > 0.85 and s < 0.25


def walk(text, ctx=None):
    i, rules = 0, []
    while i < len(text):
        j = text.find('{', i)
        if j < 0: break
        head = text[i:j].strip(); depth, k = 1, j + 1
        while k < len(text) and depth:
            depth += {'{': 1, '}': -1}.get(text[k], 0); k += 1
        body = text[j + 1:k - 1]
        if head.startswith('@media') or head.startswith('@supports'): rules += walk(body, head)
        elif head.startswith('@') or head.startswith(':root'): pass
        elif head: rules.append((ctx, head, body))
        i = k
    return rules


out = ['/* GENERATED by scripts/gen_light_theme.py — do not edit by hand. Light-theme overrides for hard-coded dark colours in app.css. */']
by_ctx = {}
KEEP = ('.story', '.bizcard', '.lvl-modal', '.mb-badge', '.nav-badge', '.badge-modal-icon', '.xp-pop', '.confetti')
for ctx, sel, body in walk(src):
    if has_white_text(body) or any(k in sel for k in KEEP): continue
    decls = tx_props(body)
    if not decls: continue
    sels = ', '.join(f'html[data-theme="light"] {s.strip()}' for s in sel.split(','))
    by_ctx.setdefault(ctx, []).append(f'{sels} {{\n' + '\n'.join(decls) + '\n}')
for ctx, rs in by_ctx.items():
    out.append('\n'.join(rs) if ctx is None else f'{ctx} {{\n' + '\n'.join(rs) + '\n}')
open(os.path.join(ROOT, 'app', 'theme-light.generated.css'), 'w', encoding='utf8').write('\n'.join(out) + '\n')
print('rules emitted:', sum(len(v) for v in by_ctx.values()))
