// Writes config.js from .env (local) or process.env (Netlify build). Only public values are written.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
const env = { ...process.env };
if (existsSync('.env')) for (const l of readFileSync('.env', 'utf8').split(/\r?\n/)) { const m = l.match(/^([A-Z_]+)=(.*)$/); if (m && !env[m[1]]) env[m[1]] = m[2].trim(); }
const url = env.SUPABASE_URL || '', key = env.SUPABASE_ANON_KEY || '';
if (/service_role/.test(key) || (key.split('.')[1] && /service_role/.test(Buffer.from(key.split('.')[1], 'base64').toString()))) { console.error('Refusing: that is a service_role key. Use the anon/publishable key.'); process.exit(1); }
writeFileSync('config.js', `// GENERATED by scripts/sync-env.mjs from .env. Public values only.\nexport const CONFIG = {\n  SUPABASE_URL: ${JSON.stringify(url)},\n  SUPABASE_ANON_KEY: ${JSON.stringify(key)},\n};\n`);
console.log(`config.js written (url ${url ? 'set' : 'EMPTY'}, anon key ${key ? 'set' : 'EMPTY'})`);
